### ISSUE TITLE
Plotly-Orca is in v1.3.1, not v3.3.5

### ISSUE THREAD

**Issue by jpn--** [conda-forge/plotly-orca-feedstock#2]
This feedstock has merged in changes from a Plotly-orca release tagged "v3.3.5", but that's not a public-facing version.  The version 3 tags are for on-prem releases, as noted in plotly/orca#286 .  The correct version of plotly-orca is 1.3.1.

And: the conda-forge version of plotly-orca seems to be broken, to the point of breaking the creation of environments where users unknowingly try to install this package, instead of getting it from the plotly channel directly, where it is also hosted (and more successfully).  It is not clear to me if this breakage is a direct result of using the wrong version, or is a separate problem.

**Comment by rluria14** [comment]
@jpn-- thanks for the heads up. v1.3.1 has been merged.

**Comment by hadim** [comment]
3.3.5 is still on the channel and get installed when no version is specified. Could you ask a dev to remove that version please?
